sources:
  - ./my_main_target_folder
  - ./Pods/MockBalm
templates:
  include:
    - SourceryTemplates/Test
  exclude:
    - SourceryTemplates/Test/LocalImports.stencil
output:
  ./my_test_target-folder/generated
