//
//  AutoMockable.swift
//  appstarter-pod-ios
//
//  Created by Gabrielle Earnshaw on 17/07/2019.
//

import Foundation

/// An empty protocol to signal that a type should have mocks generated by sourcery
public protocol AutoMockable {}
